### ISSUE TITLE
PHP problem in Debian 12 and PHP version 8.2.7

### ISSUE THREAD

**Issue by didzejj** [BartekSz95/phpvirtualbox#10]
Hi,
I have a problem with phpvirtualbox Version 7.0 (Release Candidate 1).
When I try to login I receive "An unknown PHP error occurred. This is most likely a syntax error in config.php in phpVirtualBox's folder. The most common errors are an unclosed quote or a missing semicolon in a configuration item that has been entered (e.g. location, username, or password).
Depending on your PHP configuration, navigating directly to [config.php](http://192.168.100.1/phpvirtualbox/config.php) in your web browser may display the PHP error message. ..."

My system is Debian 12, PHP version 8.2.7 and VirtualBox installd ist 7.0.10.
This version should be work with PHP 8.2, but I don't know what about 8.2.7 version.

How can I resolve it?

Regards

**Comment by BartekSz95** [comment]
I'm using newest PHP version on Debian testing and Windows Server, this works on both without problem, so I don't what is wrong with files on your server.

**Comment by didzejj** [comment]
What kind of www server do you use ?

**Comment by BartekSz95** [comment]
> What kind of www server do you use ?

Newest version of Apache 2.4.

**Comment by didzejj** [comment]
As mine. I have 2.4.57. Ok, I'll try to find a way. Thanks.
Ps. Are you from Poland Bartek ?

**Comment by didzejj** [comment]
I found solution: missing packages php-xml php8.2-xml . After I installed those packages all works fine.
Regards

**Comment by BartekSz95** [comment]
> I found solution: missing packages php-xml php8.2-xml . After I installed those packages all works fine.
> Regards

Good to hear that the problem was with this dependence.
