### ISSUE TITLE
SOLVED_This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by flintstoney** [BartekSz95/phpvirtualbox#11]
Hello friends. 
When i try to pass the http://localhost:18083 link browser shows me:
![2023-11-03_10-53](https://github.com/phpvirtualbox/phpvirtualbox/assets/59313101/5d6a7410-6874-4fe2-bb12-f0c0835ab9c3)

if I try to pass http://localhost/phpvirtualbox/ i see: An unknown PHP error occurred. This is most likely a syntax error in config.php in phpVirtualBox's folder.
![xxx](https://github.com/BartekSz95/phpvirtualbox/assets/59313101/257a7ef9-d773-444b-bc57-12025a1ff36f)

with the apache is the same. 

I am runing Arch Linux OS
PHP - 8.2.12
VirtualBox - 7.0.12 r159484

I tried diferent methods but nothing doesn't work. What can I do to solve it? Installed modules php82-xml and php-xmlrpc but this not worked for me.

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vbox="http://www.virtualbox.org/">
<SOAP-ENV:Body>
<SOAP-ENV:Fault>
<faultcode>SOAP-ENV:Client</faultcode>
<faultstring>HTTP GET method not implemented</faultstring>
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by BartekSz95** [comment]
Do you configure VBox? You have something wrong in here.

**Comment by flintstoney** [comment]
I added the vb username and password in config.php
![2023-11-05_10-44](https://github.com/BartekSz95/phpvirtualbox/assets/59313101/bf0ec61f-9db7-44d4-993a-b7244df142a9)

about vboxweb.service I almost did nothing. Just made possibility to start service from non root. 
![2023-11-05_10-35](https://github.com/BartekSz95/phpvirtualbox/assets/59313101/4c381c65-40c7-4d33-b296-5555747a36d2)

Also, I creaded the /etc/default/virtualbox file:
![2023-11-05_10-47](https://github.com/BartekSz95/phpvirtualbox/assets/59313101/43486046-015c-4eaa-b4bd-44008b846dfb)

the user vboxadmin is created and added to vboxusers group:
![2023-11-05_10-53](https://github.com/BartekSz95/phpvirtualbox/assets/59313101/96ece0bd-11ec-465e-a39b-736cf1841edc)

**Comment by flintstoney** [comment]
it was a problem with configs apache+php now is all ok
