### ISSUE TITLE
LINUX ISSUE vboxweb-service

### ISSUE THREAD

**Issue by EKI-INDRADI-PRIEDS** [BartekSz95/phpvirtualbox#17]
im install virtualbox using deb files 

default service  
/lib/systemd/system/vboxweb-service.service 

sudo mkdir -p /etc/default 
sudo nano /etc/default/virtualbox 

```sh
VBOXWEB_USER=remote_vbox
VBOXWEB_HOST=192.168.100.106
```

systemctl stop vboxweb-service.service
systemctl start vboxweb-service.service

in php virtualbox still error (after login) :

 ```php
 phpVirtualBox
Exception Object
(
    [message:protected] => Could not connect to host (http://192.168.100.106:18083/)
    [string:Exception:private] => 
    [code:protected] => 64
    [file:protected] => /var/www/vbox.rnd/endpoints/api.php
    [line:protected] => 134
    [trace:Exception:private] => Array
        (
        )

    [previous:Exception:private] => 
)
 ```

**Comment by BartekSz95** [comment]
This isn't problem with phpVirtualBox, but with your vboxsrv configuration. Just put ``systemctl status vboxweb-service`` and I think isn't run.

**Comment by EKI-INDRADI-PRIEDS** [comment]
systemctl status vboxweb-service  running but has issue 

web ui using : 
[Version 7.0 (Release Candidate 1) for VirtualBox 7.0](https://github.com/BartekSz95/phpvirtualbox/releases/tag/v7.0-rc1)

its posible to use version 7 latest ?
