### ISSUE TITLE
Error message if system only have PHP 7 or below?

### ISSUE THREAD

**Issue by urashimamei** [BartekSz95/phpvirtualbox#9]
If the host machine only installed PHP 7 or below, the dialog of error message shows 500 internal error.
Is there any chance that it could show a more specific error message like "PHP failed"? 
Or what files and how to achieve this If I want to do this myself?

Thanks for any advice!!

**Comment by urashimamei** [comment]
Hi,
Is anyone still maintaining this project? 

I met another problem that when changing language from File > Preferences > Languages, it only set the browser cookie but  does not modifying config.php. I know that Cookies has the priority, but this this wired because it would always the default language (English) when open in a new browser. Any advice or patch for it?

**Comment by BartekSz95** [comment]
> Hi,
> Is anyone still maintaining this project? 
> 
> I met another problem that when changing language from File > Preferences > Languages, it only set the browser cookie but  does not modifying config.php. I know that Cookies has the priority, but this this wired because it would always the default language (English) when open in a new browser. Any advice or patch for it?
> 
> 

This script never edit config.php file. You can change line on config file which force to use your language as primary.

**Comment by urashimamei** [comment]
Thank you for your reply. It's nice to know that this project is still on working:)))

So if I want to perform the feature that change config.php at the same time, I have to add functions at both js and php files, is that right? If so, I will try myself...

**Comment by BartekSz95** [comment]
> Thank you for your reply. It's nice to know that this project is still on working:)))
> 
> So if I want to perform the feature that change config.php at the same time, I have to add functions at both js and php files, is that right? If so, I will try myself...
> 

If you want, you can create installer or something similar and you can put pulk request on this repository, I'm open for new things. I don't have enough time right now to create new stuff in here.
